// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Message string `json:"message"`
}

type OrderReq struct {
	Id int64 `path:"id"`
}

type HandleInfo struct {
	Information string `json:"information"`
}

type OrderReply struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender string `json:"gender"`
}
