// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"
	"rpc-common/types/user"

	"user/internal/logic"
	"user/internal/svc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) CreateUser(ctx context.Context, in *user.UserInfo) (*user.UserInfo, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *user.IdRequest) (*user.UserInfo, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
