version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - $PWD/nginx/confg/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/log:/var/log/nginx
      - $PWD/nginx/html:/usr/share/nginx/html
    networks:
      project_net:
        ipv4_address: 172.18.0.2

  redis:
    image: redis:latest
    volumes:
      - $PWD/redis/confg/redis.conf:/etc/redis/redis.conf
      - $PWD/redis/data:/data
    networks:
      project_net:
        ipv4_address: 172.18.0.3

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - $PWD/mysql/my.cnf:/etc/mysql/my.cnf
      - $PWD/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      project_net:
        ipv4_address: 172.18.0.4

  mongo:
    image: mongo:latest
    volumes:
      - $PWD/mongo/confg:/data/configdb
      - $PWD/mongo/data:/data/db
    ports:
      - "27017:27017"
    networks:
      project_net:
        ipv4_address: 172.18.0.5

  geth:
    image: ethereum/client-go:latest
    volumes:
      - $PWD/geth/chain_data/genesis.json:/dapp/genesis.json
      - $PWD/geth/chain_data:/dapp
    stdin_open: true
    tty: true
    entrypoint: ["/bin/sh","/dapp/entrypoint.sh"]
    networks:
      project_net:
        ipv4_address: 172.18.0.6

  geth_server:
    build: ./geth_server
    volumes:
      - $PWD/keystore:/usr/local/geth_server/keystore
    depends_on:
      - geth
    networks:
      project_net:
        ipv4_address: 172.18.0.7

  gin_server:
    build: ./gin_server
    depends_on:
      - geth_server
      - redis
      - mongo
      - mysql
      - nginx
    networks:
      project_net:
        ipv4_address: 172.18.0.8

networks:
  project_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1