// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"middlewares/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.UserMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/login",
					Handler: loginHandler(serverCtx),
				},
			}...,
		),
	)
	server.AddRoutes([]rest.Route{
		{
			Method:  http.MethodGet,
			Path:    "/register",
			Handler: registerHandler(serverCtx),
		},
	})
}
