version: "3.8"
services:
  Etcd:
    image: bitnami/etcd:latest
    deploy:
      replicas: 1
#      restart_policy:
#        condition: on-failure
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    privileged: true
    volumes:
      - ${PWD}/data:/bitnami/etcd/data
    ports:
      - "2379:2379"
      - "2380:2380"

#"msg":"failed to start etcd","error":"cannot access data directory: open /bitnami/etcd/data/.touch: permission denied" 给目录加777权限   chmod a+rwx ./data