version: "3.8"
services:
  system:
    build: ./
    container_name: server_system
    ports:
      - "6666:6666"
    volumes:
      - /usr/local/app-file
    networks:
      - new
    depends_on:
      - db
  db:
    image: "mysql:latest"
    container_name: mydb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - new
networks:
  new:
    driver: bridge
