// Code generated by goctl. DO NOT EDIT.
package types

type RegisterReq struct {
	Name   string `json:"name"`
	Gender string `json:"gender"`
}

type RegisterResp struct {
	Status string `json:"status"`
	Data
}

type Data struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender string `json:"gender"`
}
